FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runtime

# Install ffmpeg and ffprobe
RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/package.json ./

RUN apk add --no-cache postgresql-client

CMD ["node", "dist/worker"]
